DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS token;

CREATE OR REPLACE TABLE token (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    uuid VARCHAR(36) UNIQUE DEFAULT UUID(),
    expire_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE client (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    uuid VARCHAR(36) UNIQUE DEFAULT UUID(),
    email VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(500) NOT NULL,
    password_salt VARCHAR(36) UNIQUE DEFAULT UUID(),
    redirect_uri VARCHAR(100) NOT NULL DEFAULT '',
    code VARCHAR(100) NOT NULL DEFAULT '',
    scope VARCHAR(100) NOT NULL DEFAULT '',
    state VARCHAR(100) NOT NULL DEFAULT '',
    access_token_id BIGINT REFERENCES token(id),
    refresh_token_id BIGINT REFERENCES token(id)
);
