DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS token;

CREATE OR REPLACE TABLE token (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    uuid TEXT UNIQUE DEFAULT UUID(),
    expire_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE client (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    uuid TEXT UNIQUE DEFAULT UUID(),
    redirect_uri TEXT NOT NULL DEFAULT '',
    code TEXT NOT NULL DEFAULT '',
    scope TEXT NOT NULL DEFAULT '',
    state TEXT NOT NULL DEFAULT '',
    acess_token_id BIGINT REFERENCES token(id),
    refresh_token_id BIGINT REFERENCES token(id)
);
