/*
 * snodec-control - Out-of-tree companion tool for SNode.C applications
 * Copyright (C) Volker Christian <me@vchrist.at>
 *               2020, 2021, 2022, 2023, 2024, 2025, 2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "Materializer.h"

#include <algorithm>
#include <cctype>
#include <sstream>

namespace snodec::control {

    namespace {

        bool isSafeUnquotedValue(const std::string& value) {
            if (value.empty()) {
                return false;
            }

            return std::all_of(value.begin(), value.end(), [](char character) {
                return std::isalnum(static_cast<unsigned char>(character)) != 0 || character == '.' || character == '-' ||
                       character == '_' || character == '/' || character == ':';
            });
        }

        std::string formatValueForIni(const std::string& value) {
            if (isSafeUnquotedValue(value)) {
                return value;
            }

            std::string quoted = "\"";
            for (const char character : value) {
                if (character == '"' || character == '\\') {
                    quoted.push_back('\\');
                }
                quoted.push_back(character);
            }
            quoted.push_back('"');

            return quoted;
        }

        void writeDescription(std::ostringstream& out, const std::string& description) {
            std::istringstream descriptionStream(description);
            std::string descriptionLine;

            while (std::getline(descriptionStream, descriptionLine)) {
                out << "# " << descriptionLine << "\n";
            }
        }

    } // namespace

    std::string materialize(const ConfigModel& model, const std::string& targetPath) {
        std::ostringstream out;

        out << "# Materialized configuration generated by snodec-control\n";
        out << "# Target application: " << targetPath << "\n";
        out << "#\n";
        out << "# This file is derived from the target's `-s`/`--show-config` output. Values below are\n";
        out << "# either the active value reported by the target, its default value, or empty when\n";
        out << "# neither is known. Options marked REQUIRED must be set before the target can run.\n";
        out << "\n";

        for (const ConfigSection& section : model.sections) {
            if (!section.name.empty()) {
                out << "[" << section.name << "]\n";
            }

            for (const ConfigOption& option : section.options) {
                if (!option.description.empty()) {
                    writeDescription(out, option.description);
                }

                if (option.required) {
                    out << "# REQUIRED: this option must be configured\n";
                }

                std::string value;
                if (option.hasActiveValue && option.activeValue.has_value()) {
                    value = *option.activeValue;
                } else if (option.defaultValue.has_value()) {
                    value = *option.defaultValue;
                }

                out << option.key << "=" << formatValueForIni(value) << "\n\n";
            }
        }

        return out.str();
    }

} // namespace snodec::control
