# Evaluated by CPack after release/version overrides have been applied.
set(names "${CPACK_PACKAGE_NAME}\n")
set(full_requires "")
foreach(component IN LISTS CPACK_COMPONENTS_ALL)
    if(component STREQUAL "full")
        continue()
    endif()
    string(TOLOWER "${CPACK_PACKAGE_NAME}-${component}" name)
    string(TOUPPER "${component}" upper)
    string(APPEND names "${name}\n")
    set(CPACK_RPM_${upper}_PACKAGE_NAME "${name}")
    list(APPEND full_requires "${name} = ${CPACK_PACKAGE_VERSION}-${CPACK_RPM_PACKAGE_RELEASE}")
endforeach()
list(JOIN full_requires ", " CPACK_RPM_FULL_PACKAGE_REQUIRES)
set(CPACK_DEBIAN_PACKAGE_BREAKS "${CPACK_PACKAGE_NAME} (<< ${CPACK_PACKAGE_VERSION})")
set(CPACK_DEBIAN_PACKAGE_REPLACES "${CPACK_PACKAGE_NAME} (<< ${CPACK_PACKAGE_VERSION})")
# Publication inventory comes from the same component model as the packages.
file(MAKE_DIRECTORY "${CPACK_OUTPUT_FILE_PREFIX}")
file(WRITE "${CPACK_OUTPUT_FILE_PREFIX}/${CPACK_PACKAGE_NAME}.packages" "${names}")
